version: "3"

services:

  redis:
    image: redis
    container_name: redis-service
    ports:
      - "6379:6379"
    networks:
      - socials-network

  database1:
    image: mysql
    container_name: mysql-db1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=socials_user
    ports:
      - "3307:3306"
    networks:
      - socials-network

  database2:
    image: mysql
    container_name: mysql-db2
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user_image
    ports:
      - "3308:3306"
    networks:
      - socials-network

  database3:
    image: mysql
    container_name: mysql-db3
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=user_profile
    ports:
      - "3309:3306"
    networks:
      - socials-network

  naming-server:
    image: naming-server
    container_name: naming-server-service
    ports:
      - "8761:8761"
    networks:
      - socials-network

  gateway:
    image: gateway
    container_name: gateway-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - socials-network
    depends_on:
      - naming-server

  identity-service:
    image: identity-service
    container_name: identity-service
    restart: always
    ports:
      - "6969:6969"
    networks:
      - socials-network
    depends_on:
      - naming-server
      - gateway
      - database1
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=socials_user

  image-service:
    image: image-service
    container_name: image-service
    restart: always
    ports:
      - "8085:8085"
    networks:
      - socials-network
    depends_on:
      - naming-server
      - gateway
      - database2
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=user_image


  user-profile:
    image: user-profile
    container_name: user-profile-service
    restart: always
    ports:
      - "8082:8082"
    networks:
      - socials-network
    depends_on:
      - naming-server
      - gateway
      - database3
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=user_profile

networks:
  socials-network:
    driver: bridge